name: forestvpn_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  responsive_framework: ^0.1.5
  equatable: ^2.0.3
  fluttertoast: ^8.0.9
  extended_sliver: ^2.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  injectable_generator: ^1.5.2
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro-Regular.otf
  